openapi: "3.0.3"

info:
  title: "Quiz Api"
  version: "1.0.0"

servers:
  - url: "http://localhost/"
    description: "検証環境"

paths: 
  "/":
    get:
      summary: get all quiz for user
      deprecated: false
      responses:
        "200":
          description: "成功！"
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/quiz"

components:
  schemas:
    quiz:
      type: object
      required:
        - id
        - content
        - img
      properties:
        id:
          type: integer
          format: int64
          example: 1
        content:
          type: string
          example: "gitとgithubの違いって何？"
        img:
          type: string
          example: "image.jpg"
        created_at:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00Z
        updated_at:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00Z
        deleted_at:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00Z


